// ═══════════════════════════════════════════
// 原理卡：跨菜可迁移的规则。触发条件 + 规则 + 为什么。
// 知识以「原理」为单位存储，而不是以「菜」为单位——
// 这样换个食材也能命中同一条规则（去腥不再绑在虾上）。
// ═══════════════════════════════════════════

const PRINCIPLES = [
  {
    id:'qu-xing',
    name:'去腥',
    emoji:'🐟',
    trigger:'一切动物性食材：肉、禽、鱼、虾、贝类',
    rule:'动物性食材默认都有腥味，别怀疑自己。腥味按来源分四种，对号入座：',
    branches:[
      {source:'血水（排骨/鸡肉/猪肉）',fix:'冷水下锅焯水，加料酒+姜片。水开撇掉浮沫再捞出来'},
      {source:'腥线（虾）',fix:'开背，挑出背上那条黑线'},
      {source:'黏液黑膜（鱼肚子）',fix:'刮掉肚子里的黑膜，铺姜丝一起蒸'},
      {source:'泥沙（蛤蜊/花甲）',fix:'盐水泡2小时吐沙，再焯水到开口。焯出来的汤默认别用——腥'},
    ],
    why:'记住一句口诀：肉类先焯水，海鲜重姜酒，贝类必吐沙。做完这步，后面随便做都不会腥。',
    relatedRecipes:['bai-zhuo-xia','suan-ni-bai-rou','kou-shui-ji-tui','shui-zhu-ji-xiong']
  },
  {
    id:'huo-hou',
    name:'火候三档',
    emoji:'🔥',
    trigger:'燃气灶上一切煎、炒、炖、煮',
    rule:'不看时间，看火焰和锅里的状态：',
    branches:[
      {source:'大火',fix:'火焰舔到锅底边缘、锅底全被火包住。用来炒菜、烧开水。锅里水会剧烈翻滚'},
      {source:'中火',fix:'火焰刚舔到锅底、锅底约一半有火。用来煎、炸、收汁。锅里水冒大泡'},
      {source:'小火/最小火',fix:'火焰只剩一两个小蓝点。用来炖、焖、煮肉。锅里水微微冒泡，不翻滚'},
    ],
    why:'大火让食材表面快速封住（保住嫩），小火让内部慢慢熟透（不会柴）。分不清的时候记住：炒菜怕溅油用中火起步，煮肉想嫩用小火，烧开水用大火。',
    relatedRecipes:['bai-zhuo-xia','shui-zhu-ji-xiong','suan-ni-bai-rou']
  },
  {
    id:'shu-mei-shu',
    name:'熟没熟，信食材不信时间',
    emoji:'⏱️',
    trigger:'所有“要煮多久/会不会不熟”的疑问',
    rule:'教程写的时间是以理想操作速度为前提的——你切得慢、下锅慢，时间就失真。唯一可靠的是食材自己的变化：',
    branches:[
      {source:'虾',fix:'卷成C形=正好。直=生，卷成O形=老了'},
      {source:'肉块（鸡腿/排骨/五花）',fix:'筷子能轻松戳穿最厚处，没有血水渗出'},
      {source:'肉片/肉丁',fix:'变色、筷子夹开中间没有粉色'},
      {source:'叶菜/菌菇',fix:'颜色变深、整体变软'},
      {source:'土豆/红薯/山药',fix:'筷子轻松戳穿，中间没有硬芯'},
    ],
    why:'为什么白灼虾听C形不听“变色”？虾入水瞬间就变红，变色信号来得太早，按它捞出来不熟。C形是肌肉收缩到位的信号，误差小。以后看到别的教程说“变色就行”，以这个为准——给你一个唯一口径，你就有了裁决能力。',
    relatedRecipes:['bai-zhuo-xia','shui-zhu-ji-xiong','zheng-tu-dou','bai-zhuo-xi-lan-hua']
  },
  {
    id:'fu-re',
    name:'剩菜复热',
    emoji:'♨️',
    trigger:'中午炒一锅，晚上热了吃（盖浇饭）',
    rule:'你的节奏是“一锅吃两顿”，所以存和热是必修：',
    branches:[
      {source:'哪些适合隔顿',fix:'炖/烧/卤/蒸肉——越放越入味（红烧肉第二天是巅峰）。不适合的：绿叶菜（回锅发黄）、清炒虾仁海鲜（回锅变老）、凉拌菜（出水变味）'},
      {source:'怎么存',fix:'做熟后2小时内进冰箱，别等凉透！分装饭盒，吃多少热多少'},
      {source:'怎么热',fix:'微波炉盖盖中火，中途翻动一次；回锅炒加一勺水防干；炖菜隔水蒸最好'},
      {source:'还能不能吃',fix:'闻+看+尝。有酸味、发黏、颜色不对就倒掉，别心疼'},
    ],
    why:'“放凉了再进冰箱”是最大的误区：常温多放一小时，细菌多翻一倍。热菜直接进冰箱不伤冰箱，放心。',
    relatedRecipes:['suan-ni-bai-rou','fen-zheng-rou','dou-chi-zheng-pai-gu']
  },
  {
    id:'sheng-shou-bi',
    name:'生熟体积差',
    emoji:'📏',
    trigger:'抓了一把食材，不知道做出来是多是少',
    rule:'食材分三种性格，对号入座：',
    branches:[
      {source:'膨胀型（下锅变多）',fix:'干面（一小把=一大碗）、米饭（半杯米=一碗饭）、木耳银耳（两三朵=一盘；抓一把=一盆，重灾区！）'},
      {source:'收缩型（下锅变少）',fix:'绿叶菜（一大捆焯完一小坨，放心大胆放）、肉类（缩到7-8成）、菌菇'},
      {source:'稳定型（基本不变）',fix:'土豆、萝卜、豆腐——切多大熟多大'},
    ],
    why:'口诀：膨胀“看着少一点”，收缩“看着多一点”，干货“手指抓，别手抓”。核心：用熟后当基准，配菜目标=面的1/2这种比例，装碗时看一眼就能判断，不用在切菜时预测。',
    relatedRecipes:['shui-zhu-bo-cai','bai-zhuo-xi-lan-hua','suan-rong-jin-zhen-gu','shui-zhu-mian']
  },
  {
    id:'she-you-an-quan',
    name:'涉油安全',
    emoji:'⚠️',
    trigger:'煎、炒、炸、淋热油——一切热油时刻',
    rule:'先防溅，再学会起火怎么办：',
    branches:[
      {source:'防溅四件套',fix:'①食材用厨房纸擦干再下锅（水遇热油=炸）②锅先烧干再倒油 ③沿锅边慢慢下，别往锅心砸 ④中火起步，别一上来就大火'},
      {source:'油锅起火了',fix:'关火+盖锅盖，压死别开。严禁浇水！水遇油火=爆。等火灭了再揭盖'},
      {source:'油溅到身上',fix:'立刻关火，后退一步，用凉水冲。小烫伤先冲凉水，别抹牙膏'},
    ],
    why:'第一次怕溅油是正常的。防溅四件套做完，风险已经很低。锅里有什么动作不放心，就先关火再操作——关火是你的暂停键，用它不丢人。',
    relatedRecipes:['suan-rong-xi-lan-hua','fan-qie-chao-dan','cong-you-jin-zhen-gu']
  },
  {
    id:'huo-wu-chu-li',
    name:'活物先麻醉',
    emoji:'🧊',
    trigger:'处理会动会跳的活物：活虾、活鱼、活蟹',
    rule:'别硬刚，先麻醉——低温让活物变迟钝，这是标准操作，不是偷懒：',
    branches:[
      {source:'活虾',fix:'装保鲜袋，冷冻层放 5-10 分钟（或冰水泡 5 分钟）。虾变迟钝不跳了再处理。冰镇不会杀死它，处理完照样新鲜'},
      {source:'活鱼',fix:'买的时候让摊主帮忙宰杀最省事。自己来：先用力敲头一下，一下到位，别反复'},
      {source:'活蟹',fix:'冷冻层放 10-15 分钟再上锅蒸，蒸的时候蟹腿不会挣扎'},
    ],
    why:'怕活物弹跳是正常的，不是胆小。冰镇、敲头都是专业处理手法，只是从来没人教过新手这一步。',
    relatedRecipes:['bai-zhuo-xia']
  },
  {
    id:'wei-dao-yan-shou',
    name:'味道验收三问',
    emoji:'👅',
    trigger:'出锅前试吃，判断这菜到底行不行',
    rule:'别整体问“好不好吃”——整体判断你会懵。拆成三层，尝一口，各答一遍：',
    branches:[
      {source:'咸吗（底味）？',fix:'不咸→补一点点盐或生抽；太咸→加糖+水，或再扔点配菜进去稀释'},
      {source:'鲜吗（主味）？',fix:'不鲜→加生抽/蚝油，或一小撮糖提鲜'},
      {source:'香吗（热菜）？',fix:'不香→淋一点热油，或补一把蒜末炒两下'},
    ],
    why:'缺哪层补哪层，一次只补一样，补完再尝。咸了别慌：加糖加水是标准解法，不是黑暗料理。',
    relatedRecipes:['bai-zhuo-xi-lan-hua','suan-ni-bai-rou','fan-qie-chao-dan']
  },
  {
    id:'kou-gan-mu-biao',
    name:'口感目标',
    emoji:'🎯',
    trigger:'做到“熟了”但不确定对不对',
    rule:'好吃不止“熟”，还有口感。每道菜有自己的口感目标，看菜谱上的标注，按目标停手：',
    branches:[
      {source:'脆',fix:'西兰花/黄瓜/豆芽。别久煮，变色就停——熟和脆之间只差30秒'},
      {source:'嫩',fix:'鸡丁/虾/蒸蛋。上浆+快炒+中小火，别大火干烧'},
      {source:'软糯',fix:'土豆/红薯/排骨。炖够时间，筷子戳透才算'},
      {source:'弹',fix:'白灼虾。卷成C形，多一秒都是O形'},
    ],
    why:'熟和脆之间差30秒，熟和烂之间差1分钟。目标决定你什么时候停手——菜谱里写了口感目标的，就按它来，别停在“熟了”。',
    relatedRecipes:['bai-zhuo-xia','bai-zhuo-xi-lan-hua','zheng-shui-dan','suan-rong-fen-si-xia']
  },
];

// ═══════════════════════════════════════════
// 食材卡：拿到一个食材不慌。第一入口——按食材查，而不是按菜查。
// ═══════════════════════════════════════════

const INGREDIENTS = [
  {
    id:'ji-xiong',
    name:'鸡胸肉',
    emoji:'🍗',
    about:'鸡身上最瘦的部位，便宜、高蛋白，但天生容易柴。柴不是你的问题，是这食材的脾气。',
    fresh:'粉红色不发灰，按压能回弹，没有异味。发灰发黏=别买。',
    keep:'冷藏1-2天；冷冻可放1个月。冷冻解冻：放冷藏层过夜，别泡水（泡水肉变柴）。',
    prep:'去腥：料酒+姜片腌10分钟。防柴关键：加一小勺淀粉抓匀（上浆），腌完再下锅。',
    shrink:'一大块约一盘，炒完缩到7-8成。',
    dishes:['shui-zhu-ji-xiong','liang-ban-ji-si'],
    principles:['qu-xing','shu-mei-shu','kou-gan-mu-biao']
  },
  {
    id:'ji-tui',
    name:'鸡腿',
    emoji:'🍗',
    about:'比鸡胸嫩、带皮更香，价格差不多，新手友好。炖、煮、白切都合适。',
    fresh:'皮色淡黄不发暗，按压回弹，无异味。',
    keep:'冷藏1-2天，冷冻1个月。',
    prep:'去腥：冷水下锅+姜片料酒。想皮脆：煮熟后过一遍凉水/冰水。',
    shrink:'一个琵琶腿约一人份。',
    dishes:['bai-qie-ji-tui','kou-shui-ji-tui','gong-bao-ji-ding','hong-shao-ji-tui'],
    principles:['qu-xing','shu-mei-shu'],
    alias:['鸡腿肉','琵琶腿','手枪腿']
  },
  {
    id:'wu-hua-rou',
    name:'五花肉',
    emoji:'🥩',
    about:'肥瘦相间，红烧、回锅、白切都靠它。便宜大碗，超市打折常客。注意：瘦肉替不了它——煸油出香靠的是肥肉，手里是瘦肉/里脊就去看猪瘦肉卡，别硬套小炒肉、红烧这类菜。',
    fresh:'瘦肉鲜红、肥肉洁白、按压回弹。肥肉发黄=不新鲜。',
    keep:'冷藏2天，冷冻1个月。',
    prep:'去腥：冷水下锅焯水，撇掉血沫。想不腻：煮完过冰水再切薄片。',
    shrink:'缩到7-8成，看着多其实还好。',
    dishes:['suan-ni-bai-rou','fen-zheng-rou','nong-jia-xiao-chao-rou'],
    principles:['qu-xing','shu-mei-shu','fu-re'],
    alias:['五花肉片','去皮五花肉','切片五花肉']
  },
  {
    id:'zhu-shou-rou',
    name:'猪瘦肉（里脊/瘦肉片）',
    emoji:'🥩',
    about:'超市打折常客——瘦肉片、里脊肉、纯瘦肉都是它。和五花肉是两个世界：五花肉靠煸肥油出香，瘦肉没有油可煸，天生容易柴。柴不是你的问题，是这食材的脾气——它有自己的做法（见下方预处理）。',
    fresh:'粉红色有光泽不发灰，按压回弹，没有异味。发灰发黏=别买。',
    keep:'冷藏1-2天；冷冻1个月。解冻放冷藏层过夜，别泡水（泡水肉变柴）。',
    prep:'防柴三板斧（一步都不能省）：①上浆——切好后加料酒1勺+生抽半勺+淀粉1勺抓匀，腌10分钟（没有淀粉至少料酒+食用油）②锅烧热再下，大火快炒 ③全部变白立刻盛出，绝不恋战——瘦肉两轮大火必老。注意：小炒肉、红烧这类靠肥油出香的菜，瘦肉做不了，换青椒肉丝、鱼香肉丝这类滑炒做法。',
    shrink:'缩到7-8成。',
    dishes:['qing-jiao-rou-si','yu-xiang-rou-si'],
    principles:['qu-xing','shu-mei-shu','kou-gan-mu-biao'],
    alias:['瘦肉','瘦肉片','里脊','里脊肉','猪里脊','纯瘦肉','猪肉','通脊']
  },
  {
    id:'xia',
    name:'虾',
    emoji:'🦐',
    about:'熟得飞快，是练“状态信号”最好的食材。头尾都别扔，虾头有虾黄。',
    fresh:'虾壳光亮、肉质紧实、没有浓腥味。发软发黑=不新鲜。',
    keep:'买回来当天吃掉最好。冻虾口感差一档，解冻后一定要擦干。',
    prep:'活虾先冰镇 5-10 分钟（冷冻层或冰水泡），不跳了再处理——这是标准操作，不是偷懒。开背挑虾线（腥线）。不用去虾壳，整只煮最嫩。',
    shrink:'一斤虾煮完约一盘。',
    dishes:['bai-zhuo-xia','suan-rong-fen-si-xia','xia-ren-zheng-ji-dan'],
    principles:['qu-xing','shu-mei-shu','kou-gan-mu-biao'],
    alias:['虾仁','基围虾','冻虾仁','鲜虾']
  },
  {
    id:'ge-li',
    name:'蛤蜊/花甲',
    emoji:'🐚',
    about:'便宜、鲜味足，但沙子是唯一的坑。超市晚上打折常有。',
    fresh:'壳紧闭的才新鲜。壳开着不闭的=已经死了，别买。',
    keep:'当天吃掉，别过夜。',
    prep:'盐水泡2小时以上吐沙，再下锅焯到开口。没开口的扔掉。焯出来的汤默认别用——腥。想喝汤就另起一锅清水，只放蛤蜊肉。',
    shrink:'一斤蛤蜊出半碗肉，看着少是正常的。',
    dishes:[],
    principles:['qu-xing','shu-mei-shu']
  },
  {
    id:'xi-lan-hua',
    name:'西兰花',
    emoji:'🥦',
    about:'便宜、耐放（冰箱一周没问题）、怎么做都不难。梗别扔，去皮切片比花蕾甜。',
    fresh:'颜色深绿不发黄，花蕾紧实不散。',
    keep:'冷藏一周。',
    prep:'花朝下，从花蕾中间切小朵。乒乓球大小。梗去皮切片。',
    shrink:'缩到一半体积——切的时候看着一大盘，装出来一小碗，正常，别怀疑自己加量。',
    dishes:['bai-zhuo-xi-lan-hua','suan-rong-xi-lan-hua'],
    principles:['sheng-shou-bi','kou-gan-mu-biao','shu-mei-shu']
  },
  {
    id:'jin-zhen-gu',
    name:'金针菇',
    emoji:'🍄',
    about:'便宜，熟得飞快（10秒半熟）。唯一的坑是煮太久变成橡皮筋。',
    fresh:'白色不发黄发黏，根部不发黑。',
    keep:'冷藏2-3天。',
    prep:'切掉根部土黄色部分，散成小束，冲洗沥干。',
    shrink:'缩一半。配面/配菜时按“熟后”算量。',
    dishes:['cong-you-jin-zhen-gu','suan-rong-zheng-jin-zhen-gu'],
    principles:['sheng-shou-bi','kou-gan-mu-biao','shu-mei-shu']
  },
  {
    id:'ji-dan',
    name:'鸡蛋',
    emoji:'🥚',
    about:'万能兜底：任何菜做失败了，加个蛋就是新菜。最值得练手的基础食材。',
    fresh:'泡水里沉底=新鲜；浮起来=快坏了别吃。',
    keep:'室温可放两周，夏天进冰箱。',
    prep:'打蛋时加一小撮盐，搅到蛋清蛋黄完全融合。',
    shrink:'基本不变。一人份炒蛋=2个蛋。',
    dishes:['fan-qie-chao-dan','zheng-shui-dan','zheng-wu-can-rou-dan'],
    principles:['kou-gan-mu-biao','shu-mei-shu']
  },
  {
    id:'lv-ye-cai',
    name:'绿叶菜（菠菜/生菜/小白菜）',
    emoji:'🥬',
    about:'收缩型食材的典型代表：一大捆焯完一小把。看着多很正常，别减少量。',
    fresh:'叶子挺括不发蔫，颜色鲜亮，没有烂叶。',
    keep:'冷藏2-3天，别洗了再放（洗了容易烂）。',
    prep:'根部藏泥，掰开冲。菠菜焯水时水里加点盐能去涩。',
    shrink:'缩到1/3——一人份放心抓两大把。',
    dishes:['shui-zhu-bo-cai','hao-you-sheng-cai','shui-zhu-wa-wa-cai'],
    principles:['sheng-shou-bi','shu-mei-shu'],
    alias:['菠菜','生菜','小白菜','娃娃菜','油麦菜','上海青']
  },
  {
    id:'gan-huo',
    name:'干货（木耳/香菇/银耳）',
    emoji:'🍄',
    about:'生熟比最狠的类别：抓一把木耳泡出半盆。永远“手指抓，别手抓”。',
    fresh:'干爽不潮湿，没有霉味。',
    keep:'密封阴凉处，能放半年。',
    prep:'温水泡发。木耳两三朵就够一盘。泡发后蒂头剪掉。',
    shrink:'膨胀5-10倍，重灾区！',
    dishes:['yu-xiang-rou-si','jia-chang-dou-fu'],
    principles:['sheng-shou-bi'],
    alias:['木耳','香菇','银耳','干木耳','干香菇']
  },
  {
    id:'mian-tiao',
    name:'面条',
    emoji:'🍜',
    about:'膨胀型代表：干面一小把=煮好一大碗。一碗面=硬币粗一束干面，别多抓。',
    fresh:'干面看包装，鲜面看颜色不发酸。',
    keep:'干面常温半年；鲜面冷藏2天。',
    prep:'水大开再下面，用筷子拨散防粘连。',
    shrink:'膨胀2-3倍。配菜目标：熟后总量不超过面的1/2，装碗时看一眼。',
    dishes:['fan-qie-ji-dan-mian'],
    principles:['sheng-shou-bi'],
    alias:['挂面','鲜面','手工面','细面']
  },
  {
    id:'qing-jiao',
    name:'青椒/螺丝椒',
    emoji:'🫑',
    about:'便宜、下饭神器，炒肉丝炒蛋都靠它提味。农家小炒肉、鱼香肉丝的灵魂配菜。',
    fresh:'表皮光亮挺括不发皱，蒂头翠绿。发软发皱=不新鲜。',
    keep:'冷藏3-5天，会慢慢变软，尽快吃。',
    prep:'洗净，斜切块或切丝。怕辣就去籽去筋。炒菜下锅前擦干——带水遇热油会溅。',
    shrink:'收缩一点点，基本不变。',
    dishes:['nong-jia-xiao-chao-rou','yu-xiang-rou-si'],
    principles:['she-you-an-quan','kou-gan-mu-biao']
  },
];
